#!/bin/bash
set -euo pipefail

LAYOUT_NAME="dvorak-custom"
KEYMAP_FILE="/usr/share/kbd/keymaps/xkb/${LAYOUT_NAME}.map.gz"
MKINITCPIO_CONF="/etc/mkinitcpio.conf"
CHANGED=false

echo ""
echo "[INFO] Configuring initramfs for LUKS keymap support..."

# --- Verify keymap was generated by previous script ---
if [[ ! -f "$KEYMAP_FILE" ]]; then
  echo "  ✗ Keymap file not found at $KEYMAP_FILE"
  echo "  Run the keyboard layout script first"
  exit 1
fi
echo "  ✓ Keymap file found"

# --- Ensure keyboard + keymap hooks are present and ordered before encrypt ---
HOOKS_LINE=$(grep '^HOOKS=' "$MKINITCPIO_CONF")
HOOKS_VAL=$(echo "$HOOKS_LINE" | sed -E 's/HOOKS=\((.*)\)/\1/')

# --- Skip if encrypt hook is not configured ---
if ! echo "$HOOKS_VAL" | grep -qw "encrypt"; then
  echo "  ✓ No encrypt hook found, skipping initramfs keymap setup"
  exit 0
fi

add_hook_before_encrypt() {
  local hook="$1"
  if ! echo "$HOOKS_VAL" | grep -qw "$hook"; then
    HOOKS_VAL="${HOOKS_VAL/encrypt/$hook encrypt}"
    CHANGED=true
    echo "  ✓ Added '$hook' hook"
  else
    echo "  ✓ '$hook' hook already present"
  fi
}

# Ensure correct ordering: keyboard before keymap, both before encrypt
reorder_hooks() {
  local hooks=("$HOOKS_VAL")
  local keyboard_idx=-1 keymap_idx=-1 encrypt_idx=-1

  for i in "${!hooks[@]}"; do
    case "${hooks[$i]}" in
    keyboard) keyboard_idx=$i ;;
    keymap) keymap_idx=$i ;;
    encrypt) encrypt_idx=$i ;;
    esac
  done

  local needs_reorder=false
  [[ $keyboard_idx -gt $encrypt_idx && $encrypt_idx -ne -1 ]] && needs_reorder=true
  [[ $keymap_idx -gt $encrypt_idx && $encrypt_idx -ne -1 ]] && needs_reorder=true
  [[ $keyboard_idx -gt $keymap_idx && $keymap_idx -ne -1 ]] && needs_reorder=true

  if [[ "$needs_reorder" == true ]]; then
    # Remove keyboard and keymap from current positions
    local new_hooks=()
    for hook in "${hooks[@]}"; do
      [[ "$hook" == "keyboard" || "$hook" == "keymap" ]] && continue
      new_hooks+=("$hook")
    done
    # Re-insert before encrypt
    local final_hooks=()
    for hook in "${new_hooks[@]}"; do
      [[ "$hook" == "encrypt" ]] && final_hooks+=("keyboard" "keymap")
      final_hooks+=("$hook")
    done
    HOOKS_VAL="${final_hooks[*]}"
    CHANGED=true
    echo "  ✓ Reordered hooks: keyboard keymap before encrypt"
  else
    echo "  ✓ Hook order is correct"
  fi
}

add_hook_before_encrypt "keyboard"
add_hook_before_encrypt "keymap"
reorder_hooks

# --- Write back if changed ---
if [[ "$CHANGED" == true ]]; then
  sudo sed -i "s|^HOOKS=.*|HOOKS=($HOOKS_VAL)|" "$MKINITCPIO_CONF"
  echo "  ✓ Updated HOOKS in $MKINITCPIO_CONF"
  echo "  Regenerating initramfs..."
  sudo mkinitcpio -P
  echo "  ✓ Initramfs regenerated"
else
  echo "  ✓ No changes needed, skipping mkinitcpio"
fi
