# Options to make tmux more pleasant
set -g mouse on

set -g allow-passthrough on

# Required for kitty graphics to survive pane resizes and redraws
set -ga update-environment "TERM"
set -ga update-environment "TERM_PROGRAM"

# Tell programs tmux supports truecolor + kitty-ish features
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-kitty:RGB"
set -g focus-events on

# Configure the catppuccin plugin
set -g @catppuccin_flavor "macchiato"
set -g status-position top

# Menu styling
set -g @catppuccin_menu_selected_style "fg=#{@thm_fg},bold,bg=#{@thm_overlay_0}"
# Pane styling
#
set -g @catppuccin_pane_status_enabled "yes"
set -g @catppuccin_pane_border_status "off"
set -g @catppuccin_pane_border_style "fg=#{@thm_overlay_0}"
set -g @catppuccin_pane_active_border_style "##{?pane_in_mode,fg=#{@thm_lavender},##{?pane_synchronized,fg=#{@thm_mauve},fg=#{@thm_lavender}}}"
set -g @catppuccin_pane_left_separator "█"
set -g @catppuccin_pane_middle_separator "█"
set -g @catppuccin_pane_right_separator "█"
set -g @catppuccin_pane_color "#{@thm_green}"
set -g @catppuccin_pane_background_color "#{@thm_surface_0}"
set -g @catppuccin_pane_default_text "##{b:pane_title}"
set -g @catppuccin_pane_default_fill "all"
set -g @catppuccin_pane_number_position "left"

# Window styling
set -g @catppuccin_window_status_style "custom"
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_middle_separator ""
set -g @catppuccin_window_right_separator ""
set -g @catppuccin_window_number " #I "
set -g @catppuccin_window_text " #W "
set -g @catppuccin_window_current_number " #I "
set -g @catppuccin_window_current_text " #W "

# Status line styling
set -g @catppuccin_status_background "none"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_middle_separator " "
set -g @catppuccin_status_right_separator "█"
set -g @catppuccin_status_connect_separator "yes"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_module_bg_color "#{@thm_surface_0}"

# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/catppuccin.tmux


# Status line modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{?client_prefix,#[fg=#{@thm_red}],#[fg=#{@thm_mauve}]}#[bold] #(tms sessions) "

# Load plugins
run ~/.config/tmux/plugins/tmux-cpu/cpu.tmux
run ~/.config/tmux/plugins/tmux-battery/battery.tmux

bind C-o display-popup -E "tms"
bind C-s display-popup -E "tms switch"
bind C-w display-popup -E "tms windows"
bind C-e command-prompt -p "Rename active session to: " "run-shell 'tms rename %1'"
bind C-r "run-shell 'tms refresh'"
bind C-k confirm -p "Kill current session? (y/N):" "run-shell 'tms kill'"
bind -r '(' switch-client -p\; refresh-client -S
bind -r ')' switch-client -n\; refresh-client -S

