[display]
show_time = true
greeting = "Hello Quantum!"
align_greeting = "center"
issue = false

[layout]
width = 120
window_padding = 2
container_padding = 1
prompt_padding = 1

[layout.widgets]
time_position = "top"
status_position = "bottom"

[remember]
username = true
session = true
user_session = true

[user_menu]
enabled = true
min_uid = 1000
max_uid = 60000

[secret]
mode = "characters"
characters = "*"

[keybindings]
command = 2
sessions = 3
power = 12

[session]
sessions_dirs = ["/usr/share/wayland-sessions", "/usr/share/xsessions"]
xsessions_dirs = []
environments = []

[power]
use_setsid = false

[theme]
border = "white"
text = "green"
time = "blue"
container = "black"
title = "magenta"
greet = "magenta"
prompt = "magenta"
input = "white"
action = "bright-blue"
button = "magenta"
