default_session = "default"
display_full_path = true
excluded_dirs = [
    "node_modules",
    "target",
    ".git",
]

bookmarks = ["/home/quantum", "/home/quantum/Documents/Obsidian/Main", "/home/quantum/.config/nvim"]

[popup]
width = "95%"
height = "95%"

[[search_dirs]]
path = "~/Projects/github/"
depth = 10

[[search_dirs]]
path = "~/Projects/gitlab/"
depth = 10

[shortcuts]
"tab" = "move_down"
"shift-backtab" = "move_up"
