default_session = "default"
display_full_path = true
excluded_dirs = ["node_modules", "target", ".git"]

[popup]
width = "95%"
height = "95%"

[shortcuts]
"tab" = "move_down"
"shift-backtab" = "move_up"
